package com.sh.crm.general.holders.ws.enums;

public enum MWServiceName {
    CUSTOMER_PROFILE,
    ACCOUNTS_LIST,
    ACCOUNT_TRAX,
    ACCOUNT_IBAN_SMS,
    ACCOUNT_CHEQUE_BOOK_REQUEST,
    ACCOUNT_CHEQUE_BOOK_STATUS,
    ACCOUNT_STMT,
    GET_CUSTOMER_BY_MOBILE,
    GET_CUSTOMERNO_BY_INPUT,
    GET_CUSTOMER_BY_ID,
    GET_CUSTOMER_INCOME,
    GET_ACCOUNT_TRAX,
    GET_CUSTOMER_PERSONA,
    GET_CUSTOMER_RM,
    GET_CUSTOMER_EMPLOYER_DETAILS,
    GET_CUSTOMER_SPOUSE,
    GET_CREDIT_CARDS_LIST,
    GET_CREDIT_CARDS_TRX
}
